#define BUILD_COMMIT_ID "4.5-unknown"
#define PROJECT_VERSION "8.0.5-PHFX"
#define PROJECT_VERSION_BUILD_NO "1801"
#define PROJECT_VERSION_LONG PROJECT_VERSION "." PROJECT_VERSION_BUILD_NO "(" BUILD_COMMIT_ID ")"
